spring:
    jpa.hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/ProyectoCalendario?createDatabaseIfNotExist=true
        username: root
        password: toor
        hikari:
            connecion-timeout: 60000
            maximum-pool-size: 5
